name: Executable build

on: [push, workflow_dispatch]

jobs:
  build_windows:
    env:
      CGO_ENABLED: 1
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.2
    - name: build executable
      run: go build -v -o msgreplay.exe
    - uses: actions/upload-artifact@v3
      with:
        name: windows
        path: msgreplay.exe

  build_linux:
    env:
      CGO_ENABLED: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.2
    - name: build executable
      run: go build -v -o msgreplay
    - uses: actions/upload-artifact@v3
      with:
        name: linux
        path: msgreplay

  build_macos:
    env:
      CGO_ENABLED: 1
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.2
    - name: Install SQLite 3
      run: brew install sqlite3
    - name: build executable
      run: go build -v -o msgreplay
    - uses: actions/upload-artifact@v3
      with:
        name: macos
        path: msgreplay



